### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by aman-gautam** [Deathwish98/UXGorillaQuiz#1]
Getting the following error:

`
ERROR in ./src/app/app.component.ts
Module not found: Error: Can't resolve './app.component.css' in '/Users/apple/Downloads/UXGorillaQuiz-master/ux-gorilla/src/app'
ERROR in ./src/app/navbar/navbar.component.ts
Module not found: Error: Can't resolve './navbar.component.css' in '/Users/apple/Downloads/UXGorillaQuiz-master/ux-gorilla/src/app/navbar'
`

Using the settings:

Angular CLI: 8.0.3
Node: 10.15.0
OS: darwin x64
Angular: 8.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.3
@angular-devkit/build-angular     0.800.3
@angular-devkit/build-optimizer   0.800.3
@angular-devkit/build-webpack     0.800.3
@angular-devkit/core              8.0.3
@angular-devkit/schematics        8.0.3
@angular/cli                      8.0.3
@ngtools/webpack                  8.0.3
@schematics/angular               8.0.3
@schematics/update                0.800.3
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0

Steps of reproduction:

1. Clone the repo locally
2. `cd` into the ux-gorilla folder
3. Run `npm install`
4. Run `ng build` or `ng build --prod`

**Comment by Deathwish98** [comment]
app.component.css and navbar.component.css were empty files and were not uploaded automatically due to the same reason , but had their reference in corresponding ts files. Fixed now.
